AWSTemplateFormatVersion: '2010-09-09'
Description: Template per creare variabili testuali da usare in altri template CloudFormation (export)

Parameters:  
  Environment:
    Type: String
    Default: "dev"
    Description: "Ambiente di deployment"
    AllowedValues:
      - dev
      - test
      - qa
      - uat 
      - prod
    ConstraintDescription: "Valori permessi: dev, test, qa, uat, prod"

  Project:
    Type: String
    Default: "storm-dig-workshop"
    Description: "Nome progetto"

Resources:
  Parameters:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/00_parameters"
      Type: "String"
      Value: !Sub '{"environment": "${Environment}", "project": "${Project}"}'
Outputs:
  ExportedEnvironment:
    Description: "Ambiente di deployment"
    Value: !Ref Environment
    Export:
      Name: params:env
  ExportedProject:
    Description: "Nome del progetto"
    Value: !Ref Project
    Export:
      Name: params:prj
  ExportedRegion:
    Description: "Region utilizzata"
    Value: !Ref "AWS::Region"
    Export:
      Name: params:region