AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template per il contenuto statico della web-app. Caricare manualmente i file index.html e errore.html

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: !Join 
            - '-'
            - - frontend-bucket
              - !ImportValue params:prj
              - !ImportValue params:env
        WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: error.html
        PublicAccessBlockConfiguration:
            BlockPublicAcls: false
            BlockPublicPolicy: false
            IgnorePublicAcls: false
            RestrictPublicBuckets: false
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${S3Bucket.Arn}/*'
Outputs:
  WebsiteURL:
    Description: URL of the static website
    Value: !GetAtt S3Bucket.WebsiteURL
  ExportedS3arn:
    Description: "Path S3 applicazione monolitica"
    Value: !Ref S3Bucket
    Export:
      Name: params:frontend-bucket-arn